<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Meuble;
use Illuminate\Http\Request;

class MeubleController extends Controller
{
//    public function index()
//    {
//        return parent::index(); // TODO: Change the autogenerated stub
//        return view('')
//    }

    public function index()
    {
        return view('admin.admin');
    }

    public function viewAjoutMeuble(Request $request)
    {
        $meubles = Meuble::all();
        $sortOrder = 'asc'; // Valeur par défaut
        if(request()->has('sort_order')){
            $sortOrder = request()->query('sort_order');
        }

        $meubles = Meuble::orderBy('nom', $sortOrder)->paginate(5);


        return view('admin.meuble', compact('meubles', 'sortOrder'));

    }

    public function enregistrer_meuble(Request $request)
    {
        $images = array();
        foreach($request->file('images') as $image) {
            $fileName = $request->nom . time() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('images', $fileName);
            array_push($images, $fileName);
        }

       Meuble::create([
            'nom' => $request->nom,
            'categorie' => $request->categorie,
            'couleur' => $request->couleur,
            'description' => $request->description,
            'stock' => $request->stock,
            'prix' => $request->prix,
            'photo1' => $images[0],
            'photo2' => isset($images[1]) ? $images[1] : null,
            'photo3' => isset($images[2]) ? $images[2] : null,
        ]);

        return redirect("admin/ajouter_meubles");

    }

    public function viewCategorie()
    {
        return view('admin.categorie');
    }

    public function viewCouleur()
    {
        return view('admin.couleur');
    }
}
