name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Clone or pull code
        run: |
          cd /home/debian/ecole
          if [ -d "chez-michel-commerce" ]; then
            cd chez-michel-commerce
            git pull
          else
            git clone https://github.com/Isaatox/chez-michel-commerce.git
            cd chez-michel-commerce
          fi
          cp .env.example .env
          composer install --no-interaction --no-progress --no-suggest
          php artisan key:generate
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Install dependencies
        run: |
          cp .env.example .env
          composer install --no-interaction --no-progress --no-suggest

      - name: Generate key
        run: php artisan key:generate

      - name: Configure environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Run migrations
        run: php artisan migrate --force
