name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          cp .env.example .env
          composer install --no-interaction --no-progress --no-suggest

      - name: Generate key
        run: php artisan key:generate

      - name: Configure environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Run migrations
        run: php artisan migrate --force

      - name: Deploy to OVH VPS
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 51.77.140.41
          REMOTE_USER: debian
          REMOTE_PORT: 22
          SOURCE: "/"
          TARGET: "/home/debian/ecole/"
          ARGS: "-rltgoDzvO --delete"
          EXCLUDE: ".git*"
